### ISSUE TITLE
Consider a way to handle Priority Mode for Siang Hwee

### ISSUE THREAD

**Issue by blimyj** [AY1920S1-CS2103T-T10-3/main#234]
Think of how priority mode is to be handled in the MainWindow.java.
Considerations:
1. How to lock the UI in Priority mode and Very priority mode.
2. The "correct" way to apply the function according to SE principles. (SOLID, DRY, YAGNI)

@sianghwee Did I miss out anything? 😅

**Comment by sianghwee** [comment]
Hi, I have decided to go with the implementation of putting a boolean in the `ItemModel` to specify if I am in focus mode. The other implementation will be too troublesome as it requires passing the different list back and forth among the different `ItemModel`
