### ISSUE TITLE
Clashing Event and Reminder autoreschedule period

### ISSUE THREAD

**Issue by mannggoo** [AY1920S1-CS2103T-T10-3/main#269]
- Defensively write that events that have auto CANNOT have reminders and vice versa:
      + cannot initiate reminder and -auto flag
      + cannot go from existing item with neither reminder nor auto to having both
      + cannot go from existing item with auto to have reminder as well
      + cannot go from existing item with reminder to have auto
Conclusion: ask bryan to invalidate build() if both reminder.isPresent() && event.hasAutoReschedule() in item builder (note that auto is in event)

**Comment by mannggoo** [comment]
Alternative: the only parser allowed for reminders is a "1.min.before" kind where the reminder is relative to the event time. As such, when rescheduling, the reminder will be set before. 

**Potential Bug:**
But there is also the issue where the relative difference of times is larger than the reschedule period

**Comment by blimyj** [comment]
Resolved.

**Comment by blimyj** [comment]
Resolved.
