### ISSUE TITLE
PR created by unrecognized user

### ISSUE THREAD

**Issue by damithc** [AY1920S1-CS2103T-T10-3/main#48]
This PR https://github.com/nus-cs2103-AY1920S1/addressbook-level3/pull/3 was created by an unrecognized github username, and therefore the bot is unable to tag it correctly. As a result, your PR did not receive any comments during the tutorial today. Also note that other tools used by the module will not recognize work done by unknown GitHub usernames.

**Comment by blimyj** [comment]
I have used my account @blimyj to create a PR.
