### ISSUE TITLE
Failing test case parseCommand_unrecognisedInput_throwsParseException()

### ISSUE THREAD

**Issue by sianghwee** [AY1920S1-CS2103T-T10-3/main#50]
The code is currently failing gradlew check due to it failing the following test case:
`parseCommand_unrecognisedInput_throwsParseException()`
This can be fixed by changing the `MESSAGE_INVALID_COMMAND_FORMAT` in commons.core.Messages to be a plain string without any variables to replace. 

The code also needs to be changed at the AddressBookParser.java when throwing the ParseException to just throw a plain string without String.format() as it is currently waiting for a variable but none is supplied.

Refer to the comments on merge pull request #49 to see the expected changes

**Comment by Icesiolz** [comment]
Done.
